# Generated by Django 5.0 on 2023-12-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="bookingDate",
            field=models.DateField(),
        ),
    ]
